spring:
  application:
    name: Eventos API
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/eventos}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    show-sql: true # Muestra las consultas SQL en la consola (logs)
    hibernate:
      ddl-auto: update # Crea o actualiza las tablas automáticamente

# OJO: Para HS512 necesitas una clave MUY larga (mínimo 64 caracteres)
jwt:
  secret: ${JWT_SECRET:UnaClaveMuySecretaParaFirmarTusJWTTokensYQueNadieLosFalsifiqueEsImportante}
  expiration: 600000