spring:
  application:
    name: Eventos API
  datasource:
    url: jdbc:postgresql://localhost:5432/eventos
    username: user
    password: password
  jpa:
    show-sql: true # Muestra las consultas SQL en la consola (logs)
    hibernate:
      ddl-auto: update # Crea o actualiza las tablas automáticamente

# OJO: Para HS512 necesitas una clave MUY larga (mínimo 64 caracteres)
jwt:
  secret: UnaClaveMuySecretaParaFirmarTusJWTTokensYQueNadieLosFalsifiqueEsImportante
  expiration: 600000